#! /bin/bash

#=========================================================================
# Copyright (c) 2014 Jupiter Jones & Terra Australis [Incognita] Nation (jupiter@ta-nation.org)#  
#=========================================================================

projectName="Flow"
projectDirectoryName="flow"
logFile="projectLoad_${projectName}.log"

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name>

Create project entry node for $projectName in tODE /home for named stone.

OPTIONS
  -h show usage

EXAMPLES
  $(basename $0) -h
  $(basename $0) devkit

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions

getOpts_help $@ #parse standard (-h) options

if [ $# -ne 1 ]; then
  usage; exit 1
fi
stoneName="$1"
$GS_HOME/bin/tode serverDoIt $stoneName 1> $GS_HOME/gemstone/stones/$stoneName/logs/$logFile << EOF
  | entry result |
  entry := TDProjectSpecEntryDefinition new
    baseline: '${projectName}'
      repository: 'github://GsDevKit/flow:gs_master/backend/repository'
      loads: #('default');
    status: #(#'active');
    yourself.
  result := entry createProjectEntryNode: '/home/${projectDirectoryName}'.
  ^result printString
EOF
